# Olist E-Commerce Data Analysis

## Objective

This project explores the Olist E-commerce dataset from Kaggle using SQL and Python to answer business-relevant questions related to sales performance, delivery reliability and customer satisfaction.

## Project Overview
The Olist Database contains information about:
1. Orders, including items, products and product categories
2. Customer and payment data, including geolocation information

## Business Questions Explored
1. How large is the dataset?
2. What time period does the data cover?
3. What are the top 20 product categories by revenue of the last year?
4. How many orders were placed per year and what percentage of them were delayed?
6. Which product category has the highest customer review scores?

In [17]:
import sqlite3, pandas as pd

In [18]:
conn = sqlite3.connect('./data/olist.db')

In [19]:
# Q1: How large is the dataset?
query = 'SELECT COUNT(*) AS total_orders FROM orders;'

In [20]:
display(pd.read_sql(query, conn))

   total_orders
0         99441

In [21]:
# Q2: What time period does the data cover?
q2 = 'SELECT MIN(order_purchase_timestamp) AS first_order, MAX(order_purchase_timestamp) AS last_order FROM orders;'

In [22]:
display(pd.read_sql(q2, conn))

           first_order           last_order
0  2016-09-04 21:15:19  2018-10-17 17:30:18

In [23]:
# Q3: What are the top 20 product categories by revenue of the last year?
q3 = """SELECT
    product_category_name,
        ROUND(
            SUM(
            price)/1000000.0,4
        ) AS revenue_per_mio
FROM order_items
    LEFT JOIN products ON order_items.product_id = products.product_id
GROUP BY product_category_name
ORDER BY revenue_per_mio DESC
LIMIT 20
;"""

In [24]:
display(pd.read_sql(q3, conn))

     product_category_name  revenue_per_mio
0             beleza_saude           1.2587
1       relogios_presentes           1.2050
2          cama_mesa_banho           1.0370
3            esporte_lazer           0.9880
4   informatica_acessorios           0.9120
5         moveis_decoracao           0.7298
6               cool_stuff           0.6353
7    utilidades_domesticas           0.6322
8               automotivo           0.5927
9       ferramentas_jardim           0.4853
10              brinquedos           0.4839
11                   bebes           0.4118
12              perfumaria           0.3991
13               telefonia           0.3237
14       moveis_escritorio           0.2740
15               papelaria           0.2309
16                     pcs           0.2230
17                pet_shop           0.2143
18   instrumentos_musicais           0.1915
19         eletroportateis           0.1906

In [25]:
# Q4: How many orders were placed per year and what percentage of them were delayed?
q4 = """SELECT 
    strftime("%Y", order_purchase_timestamp) AS year, 
    count(*) AS orders,
    SUM(
        CASE WHEN order_delivered_customer_date > order_estimated_delivery_date 
            THEN 1 
            ELSE 0 
        END
    ) AS delayed_orders,
    ROUND(
        100.0 * SUM(
        order_delivered_customer_date > order_estimated_delivery_date
        ) / count(*), 2
    ) AS delayed_percentage
FROM orders 
GROUP BY strftime("%Y", order_purchase_timestamp)
ORDER BY year;"""

In [12]:
display(pd.read_sql(q4,conn))

   year  orders  delayed_orders  delayed_percentage
0  2016     329               4                1.22
1  2017   45101            2878                6.38
2  2018   54011            4945                9.16

In [ ]:
# Q5: Which product category has the highest customer review scores?

In [ ]:
display(pd.read_sql(q5,conn))

In [14]:
conn.close()